default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: password
  schema_search_path: 'azafinance'
development:
  <<: *default
  database: chitter_development

test:
  <<: *default
  database: chitter_test
