default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: password

development:
  <<: *default
  database: chitter_development

production:
  <<: *default
  database: chitter_production
  username: chitter
  password: <%= ENV['CHITTER_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: chitter_test
